import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import '../assets/sass/styles.scss'
import { Inter } from 'next/font/google'
import Header from '../../shared/layouts/header'
import Footer from '../../shared/layouts/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css" />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
